export default {
    userType: '',
    config: {},
    currencys: [],
    warehouses: {},
    all_items:{},
    office:{},
    file: {},
    files:[],
    processes:[],
    actions:[],
    offices:[],
    documentTypes:[],
    customers:[],
    workers:[],
}
