export default {
    userType: '',
    showColorDialog: false,
    loading_submit: false,
    color: {},
    mold: {},
    config: {},
    currencys: [],
    warehouses: {},
    all_items:{},
    office:{},
    file: {},
    files:[],
    processes:[],
    records:[],
    colors:[],
    molds:[],
    CatItemMoldProperty:[],
    CatItemUnitBusiness:[],
    CatItemStatus:[],
    CatItemPackageMeasurement:[],
    CatItemProductFamily:[],
    CatItemUnitsPerPackage:[],
    CatItemMoldCavity:[],
    extra_colors: [],
    extra_CatItemUnitsPerPackage: [],
    extra_CatItemMoldProperty: [],
    extra_CatItemUnitBusiness: [],
    extra_CatItemStatus: [],
    extra_CatItemPackageMeasurement: [],
    extra_CatItemMoldCavity: [],
    extra_CatItemProductFamily: [],
    pagination: {
            current_page : 1,
        total : 0,
        per_page : 25,
    },
    actions:[],
    offices:[],
    documentTypes:[],
    customers:[],
    workers:[],
    company: {
        logo:'',
        name:'',
    },
    establishment: {
        address:'-',
        district: {description:''},
        province: {description:''},
        department: {description:''},
        country: {description:''},
        telephone:'-',
        email:null,
    },
}
